import {
    Stethoscope,
    AlertTriangle,
    UserCog,
    Bell,
    Settings,
    Briefcase,
    Layout,
    Package,
    Users,
    Calendar,
    FileText
} from "lucide-react";

export const MODULE_CONFIG = {
    appointments: {
        order: 1,
        label: "Citas",
        icon: Calendar,
        color: "#6366f1", // Indigo
        path: "/appointments",
        key: "F12",
    },
    patients: {
        order: 2,
        label: "Pacientes",
        icon: Stethoscope,
        color: "#0ea5e9",
        path: "/patients",
        key: "F1",
    },
    inventory: {
        order: 3,
        label: "Inventario",
        icon: Package,
        color: "#a855f7",
        path: "/inventory",
        key: "F5",
    },
    employees: {
        order: 4,
        label: "Empleados",
        icon: Users,
        color: "#10b981",
        path: "/employees",
        key: "F7",
    },
    services: {
        order: 5,
        label: "Servicios",
        icon: Briefcase,
        color: "#0ea5e9",
        path: "/services",
        key: "F3",
    },
    clinic_areas: {
        order: 6,
        label: "Áreas Clínicas",
        icon: Layout,
        color: "#0ea5e9",
        path: "/clinic-areas",
        key: "F4",
    },
    patient_alerts: {
        order: 7,
        label: "Alertas de Paciente",
        icon: AlertTriangle,
        color: "#f59e0b",
        path: "/patient-alerts",
        key: "F2",
    },
    users: {
        order: 8,
        label: "Usuarios",
        icon: UserCog,
        color: "#0ea5e9",
        path: "/users",
        key: "F8",
    },
    settings: {
        order: 9,
        label: "Configuración",
        icon: Settings,
        color: "#10b981",
        path: "/settings",
        key: "F11",
    },
    notifications: {
        order: 10,
        label: "Notificaciones",
        icon: Bell,
        color: "#ef4444",
        path: "/notifications",
        key: "F10",
    },
    reports: {
        order: 11,
        label: "Reportes",
        icon: FileText,
        color: "#6b7280",
        path: "/reports",
        key: null,
    },
};
